### ISSUE TITLE
Some elements don't display

### ISSUE THREAD

**Issue by senyzspalding** [SENYLRC/ArclightEmpireADC_legacy#4]
This is a know bug 
https://github.com/projectblacklight/arclight/issues/898#issue-501128342

We are mainly looking for note

**Comment by gwiedeman** [comment]
This issue is hard for me to look at because I don't have a working example, but it should be an easy fix. It looks like notes should be getting indexed here: https://github.com/SENYLRC/ArclightEmpireADC/blob/master/lib/arclight/traject/ead2_config.rb#L36

Adding `config.add_background_field 'note_ssm', label: 'General Note', helper_method: :render_html_tags` in the catalog controller might do it. For collection-level I would try adding it here: https://github.com/SENYLRC/ArclightEmpireADC/blob/master/app/controllers/catalog_controller.rb#L274

For the component field, try adding `config.add_component_field 'note_ssm', label: 'General Note', helper_method: :render_html_tags
` here: https://github.com/SENYLRC/ArclightEmpireADC/blob/master/app/controllers/catalog_controller.rb#L332

If you want them displayed at both levels, add both lines. There's a really long tail of EAD elements, so that's generally why it might not display all of them out-of-the-box.

Catalog Controller is an upstream Blacklight thing. There are some helpful docs here: https://github.com/projectblacklight/blacklight/wiki#blacklight-configuration
